include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - docs/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_initializing_formals: false
    prefer_single_quotes: true
    use_null_aware_elements: false
