import 'dart:async';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'linux_atomic_file_api.dart';

class AtomicFileAlreadyExistsException implements Exception {
  const AtomicFileAlreadyExistsException(this.path);

  final String path;

  @override
  String toString() => 'A filesystem entity already exists at "$path".';
}

class AtomicFileChangedException implements Exception {
  const AtomicFileChangedException(this.path);

  final String path;

  @override
  String toString() => 'The file at "$path" changed during publication.';
}

/// Publishes generated bytes without ever exposing a partially written file.
class AtomicFileWriter {
  const AtomicFileWriter();

  Future<void> writeBytes(
    String targetPath,
    List<int> bytes, {
    required bool overwrite,
    FutureOr<void> Function()? beforePublish,
    FutureOr<bool> Function(String replacedPath)? acceptReplaced,
  }) async {
    if (!Platform.isLinux) {
      throw UnsupportedError(
        'Atomic export is currently supported on Linux only.',
      );
    }
    final absoluteTarget = p.normalize(p.absolute(targetPath));
    final parent = Directory(p.dirname(absoluteTarget));
    if (!await parent.exists()) {
      throw FileSystemException(
        'The export destination directory does not exist',
        parent.path,
      );
    }

    final stagingDirectory = await parent.createTemp('.busymark-export-');
    final stagedFile = File(p.join(stagingDirectory.path, 'document.bin'));
    try {
      await stagedFile.writeAsBytes(bytes, flush: true);
      await beforePublish?.call();
      if (overwrite) {
        final targetType = await FileSystemEntity.type(
          absoluteTarget,
          followLinks: false,
        );
        if (targetType != FileSystemEntityType.notFound &&
            targetType != FileSystemEntityType.file) {
          throw FileSystemException(
            'The export destination is not a regular file',
            absoluteTarget,
          );
        }
        if (acceptReplaced != null) {
          if (targetType == FileSystemEntityType.notFound) {
            final errorNumber = LinuxAtomicFileApi.instance.publishNoReplace(
              stagedFile.absolute.path,
              absoluteTarget,
            );
            if (errorNumber == null) return;
            if (errorNumber == LinuxAtomicFileApi.fileExistsError) {
              throw AtomicFileChangedException(absoluteTarget);
            }
            throw FileSystemException(
              'Failed to atomically publish the new file',
              absoluteTarget,
              OSError('no-replace publication failed', errorNumber),
            );
          }
          final atomicApi = LinuxAtomicFileApi.instance;
          if (!atomicApi.isAvailable) {
            throw FileSystemException(
              'Conflict-safe replacement requires Linux renameat2',
              absoluteTarget,
            );
          }
          final exchangeError = atomicApi.exchange(
            stagedFile.absolute.path,
            absoluteTarget,
          );
          if (exchangeError != null) {
            throw AtomicFileChangedException(absoluteTarget);
          }
          Object? callbackError;
          StackTrace? callbackStack;
          var accepted = false;
          try {
            accepted = await acceptReplaced(stagedFile.absolute.path);
          } on Object catch (error, stackTrace) {
            callbackError = error;
            callbackStack = stackTrace;
          }
          if (!accepted || callbackError != null) {
            final rollbackError = atomicApi.exchange(
              stagedFile.absolute.path,
              absoluteTarget,
            );
            if (rollbackError != null) {
              throw FileSystemException(
                'Failed to restore a concurrently changed file',
                absoluteTarget,
                OSError('atomic rollback failed', rollbackError),
              );
            }
            if (callbackError != null) {
              Error.throwWithStackTrace(callbackError, callbackStack!);
            }
            throw AtomicFileChangedException(absoluteTarget);
          }
          return;
        }
        await stagedFile.rename(absoluteTarget);
        return;
      }

      final errorNumber = LinuxAtomicFileApi.instance.publishNoReplace(
        stagedFile.absolute.path,
        absoluteTarget,
      );
      if (errorNumber == null) {
        return;
      }
      if (errorNumber == LinuxAtomicFileApi.fileExistsError) {
        throw AtomicFileAlreadyExistsException(absoluteTarget);
      }
      throw FileSystemException(
        'Failed to atomically publish the exported file',
        absoluteTarget,
        OSError('no-replace publication failed', errorNumber),
      );
    } finally {
      await _deleteBestEffort(stagedFile);
      try {
        if (await stagingDirectory.exists()) {
          await stagingDirectory.delete();
        }
      } on Object {
        // Cleanup must not hide the write result.
      }
    }
  }

  Future<void> _deleteBestEffort(File file) async {
    try {
      if (await file.exists()) {
        await file.delete();
      }
    } on Object {
      // Cleanup must not hide the write result.
    }
  }
}
