import 'dart:io';

import 'package:path/path.dart' as p;

import 'linux_atomic_file_api.dart';

class AtomicFileAlreadyExistsException implements Exception {
  const AtomicFileAlreadyExistsException(this.path);

  final String path;

  @override
  String toString() => 'A filesystem entity already exists at "$path".';
}

/// Publishes generated bytes without ever exposing a partially written file.
class AtomicFileWriter {
  const AtomicFileWriter();

  Future<void> writeBytes(
    String targetPath,
    List<int> bytes, {
    required bool overwrite,
  }) async {
    if (!Platform.isLinux) {
      throw UnsupportedError(
        'Atomic export is currently supported on Linux only.',
      );
    }
    final absoluteTarget = p.normalize(p.absolute(targetPath));
    final parent = Directory(p.dirname(absoluteTarget));
    if (!await parent.exists()) {
      throw FileSystemException(
        'The export destination directory does not exist',
        parent.path,
      );
    }

    final stagingDirectory = await parent.createTemp('.busymark-export-');
    final stagedFile = File(p.join(stagingDirectory.path, 'document.bin'));
    try {
      await stagedFile.writeAsBytes(bytes, flush: true);
      if (overwrite) {
        final targetType = await FileSystemEntity.type(
          absoluteTarget,
          followLinks: false,
        );
        if (targetType != FileSystemEntityType.notFound &&
            targetType != FileSystemEntityType.file) {
          throw FileSystemException(
            'The export destination is not a regular file',
            absoluteTarget,
          );
        }
        await stagedFile.rename(absoluteTarget);
        return;
      }

      final errorNumber = LinuxAtomicFileApi.instance.publishNoReplace(
        stagedFile.absolute.path,
        absoluteTarget,
      );
      if (errorNumber == null) {
        return;
      }
      if (errorNumber == LinuxAtomicFileApi.fileExistsError) {
        throw AtomicFileAlreadyExistsException(absoluteTarget);
      }
      throw FileSystemException(
        'Failed to atomically publish the exported file',
        absoluteTarget,
        OSError('no-replace publication failed', errorNumber),
      );
    } finally {
      await _deleteBestEffort(stagedFile);
      try {
        if (await stagingDirectory.exists()) {
          await stagingDirectory.delete();
        }
      } on Object {
        // Cleanup must not hide the write result.
      }
    }
  }

  Future<void> _deleteBestEffort(File file) async {
    try {
      if (await file.exists()) {
        await file.delete();
      }
    } on Object {
      // Cleanup must not hide the write result.
    }
  }
}
