#!/usr/bin/env python3
"""Extract authoring rules from JetBrains' topic.v2.xsd (pass local XSD path).

Download: https://resources.jetbrains.com/writerside/1.0/topic.v2.xsd
The published XSD lags some releases; versioned overlays live in writerside_schema.dart.
"""
import hashlib
import json
import pathlib
import sys
import xml.etree.ElementTree as ET

source = pathlib.Path(sys.argv[1])
root = ET.fromstring(source.read_bytes())
ns = '{http://www.w3.org/2001/XMLSchema}'
by_kind = {kind: {node.get('name'): node for node in root.findall(ns + kind)}
           for kind in ('element', 'group', 'attribute', 'attributeGroup', 'complexType', 'simpleType')}

def effective(node):
    if node.get('type') in by_kind['complexType']:
        return by_kind['complexType'][node.get('type')]
    if node.get('substitutionGroup') and node.find(ns + 'complexType') is None:
        return effective(by_kind['element'][node.get('substitutionGroup')])
    return node

def concrete(name):
    node = by_kind['element'].get(name)
    result = set() if node is not None and node.get('abstract') == 'true' else {name}
    for child_name, child in by_kind['element'].items():
        if child.get('substitutionGroup') == name:
            result |= concrete(child_name)
    return result

def children(node, seen=frozenset()):
    result = set()
    for child in node:
        name = child.tag.removeprefix(ns)
        if name == 'element':
            result |= concrete(child.get('ref') or child.get('name'))
        elif name in ('group', 'complexType') and child.get('ref') and child.get('ref') not in seen:
            ref = child.get('ref')
            result |= children(by_kind[name][ref], seen | {ref})
        elif name in ('sequence', 'choice', 'all', 'complexType', 'complexContent', 'extension', 'restriction', 'group'):
            base = by_kind['complexType'].get(child.get('base'))
            if base is not None:
                result |= children(base, seen)
            result |= children(child, seen)
    return result

def type_info(node):
    node_type = node.get('type', 'xs:string')
    simple = node.find(ns + 'simpleType')
    if simple is None:
        simple = by_kind['simpleType'].get(node_type)
    values = []
    if simple is not None:
        values = [x.get('value') for x in simple.iter(ns + 'enumeration')]
        restriction = simple.find(ns + 'restriction')
        if restriction is not None:
            node_type = restriction.get('base', node_type)
    return node_type.removeprefix('xs:'), values

def attributes(node, seen=frozenset()):
    result = {}
    for child in node:
        kind = child.tag.removeprefix(ns)
        if kind == 'attribute':
            name = child.get('name') or child.get('ref')
            definition = by_kind['attribute'].get(child.get('ref'), child)
            typ, vals = type_info(definition)
            result[name] = (typ, vals, child.get('use', definition.get('use')) == 'required')
        elif kind == 'attributeGroup' and child.get('ref') and child.get('ref') not in seen:
            ref = child.get('ref')
            result.update(attributes(by_kind[kind][ref], seen | {ref}))
        elif kind in ('complexType', 'complexContent', 'simpleContent', 'extension', 'restriction'):
            base = by_kind['complexType'].get(child.get('base'))
            if base is not None:
                result.update(attributes(base, seen))
            result.update(attributes(child, seen))
    return result

def quoted(value):
    return json.dumps(value, ensure_ascii=False).replace('$', r'\$')
def strings(values):
    return '<String>{' + ', '.join(map(quoted, sorted(values))) + '}'

out = ["// Generated by tools/generate_writerside_schema.py. Do not edit.",
       "// ignore_for_file: prefer_single_quotes",
       "// Source: https://resources.jetbrains.com/writerside/1.0/topic.v2.xsd",
       "// SHA256: " + hashlib.sha256(source.read_bytes()).hexdigest(),
       "class WritersideSchemaElementRules {",
       "  const WritersideSchemaElementRules({required this.children, required this.attributes, required this.required, required this.values});",
       "  final Set<String> children;", "  final Map<String, String> attributes;",
       "  final Set<String> required;", "  final Map<String, Set<String>> values;", "}",
       "const writersideOfficialRules = <String, WritersideSchemaElementRules>{"]
for name, node in sorted(by_kind['element'].items()):
    if node.get('abstract') == 'true':
        continue
    node = effective(node)
    attrs = attributes(node)
    out.append(f'  {quoted(name)}: WritersideSchemaElementRules(')
    out.append('    children: ' + strings(children(node)) + ',')
    out.append('    attributes: <String, String>{' + ', '.join(quoted(k) + ': ' + quoted(v[0]) for k, v in sorted(attrs.items())) + '},')
    out.append('    required: ' + strings(k for k, v in attrs.items() if v[2]) + ',')
    out.append('    values: <String, Set<String>>{' + ', '.join(quoted(k) + ': ' + strings(v[1]) for k, v in sorted(attrs.items()) if v[1]) + '},'),
    out.append('  ),')
out.append('};')
pathlib.Path('lib/src/writerside/writerside_schema_data.dart').write_text('\n'.join(out) + '\n')
